# -*- coding: utf-8 -*-
"""calc2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWrIqpotioPlumhOBFre6GGpMFjPCX6J
"""

def add(x, y):
    z = x + y
    return z

def subtract(x, y):
    z = x - y
    return z

def multiply(x, y):
    z = x * y
    return z

def divide(x, y):
    if y !=0:
       z = x / y
    else:
       print('Делить на 0 нельзя!')
       z = 'Error'
    return z

def power(x, y):
    y = int(y)
    if y == 0:
       z = 1
    elif y > 0:
       z = 1
       for i in range(y):
           z = multiply(z, x)
    elif y < 0:
       if x == 0:
          print('Делить на 0 нельзя!')
          z = 'Error'
       else:
          z = 1
          for i in range(-y):
              z = multiply(z, x)
          z = divide(1, z)

    return z

def abs(x):
    if x >= 0:
       z = x
    elif x < 0:
       z = -x

    return z