# -*- coding: utf-8 -*-
"""complex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQ57s6gr7R65-RjkBE454t8O-l60zolS
"""

def c_add(c_x, c_y):
    c_z = complex(c_x) + complex(c_y)
    return c_z

def c_sub(c_x, c_y):
    c_z = complex(c_x) - complex(c_y)
    return c_z

def c_mult(c_x, c_y):
    c_x_r = complex(c_x).real
    c_x_i = complex(c_x).imag
    c_y_r = complex(c_y).real
    c_y_i = complex(c_y).imag
    c_z_r = c_x_r * c_y_r - c_x_i * c_y_i
    c_z_i = c_x_r * c_y_i + c_x_i * c_y_r
    c_z = complex(c_z_r, c_z_i)
    return c_z

def c_div(c_x, c_y):
    c_x_r = complex(c_x).real
    c_x_i = complex(c_x).imag
    c_y_r = complex(c_y).real
    c_y_i = complex(c_y).imag

    denom = c_y_r * c_y_r + c_y_i * c_y_i

    if denom == 0:
       print('Делить на 0 нельзя!')
       c_z = 'Error'
    else:
      c_z_r = (c_x_r * c_y_r + c_x_i * c_y_i) / denom
      c_z_i = (c_x_i * c_y_r - c_x_r * c_y_i) / denom
      c_z = complex(c_z_r, c_z_i)

    return c_z